---
title: "Data Relations"
---

## Objectives

When we analyze data, we often need to combine data from different sources to get the full picture of what's going on. For example, you might have a spreadsheet that lists students, their years, majors, and demographic information, and another spreadsheet that lists their grade history. How do you combine these tables into a single dataset? This week, we will discuss the family of "join" functions that allow us to combine different datasets. They use the overlap between datasets to smartly join them together so that you have everything in one place. This will make it easier to summarize and visualize your data going forward.

::: {.callout-note icon="false"}
## Key concepts

joining functions (`left_join`, `right_join`, `inner_join`, `full_join`), binding functions (`bind_rows`), set operations (`intersect`, `union`, `setdiff`), functions for checking your data as you go (`glimpse`, `str`, `summary`)
:::

## Readings

You should read this chapter before you come to class:

-   *Applied Data Skills -* [Chapter 7: Data Relations](https://psyteachr.github.io/ads-v3/07-joins.html)

## In-class exercises

We will follow along with the examples given in the textbook. Create an R project called `data-relations`, and save today's work in an R markdown report called `relations.Rmd`.

## Weekly assignment

Solve the following problems using the concepts you have learned in class. As always, your R markdown report should be organized with headings and comments explaining your work.

1.  Complete the [exercise](https://psyteachr.github.io/ads-v3/07-joins.html#grade-data) described in the chapter from 7.10.1 through 7.10.4.

2.  Using the `completes` dataframe that you have created, compute some summary statistics:

    a)  What is the mean and standard deviation for the number of points earned on the exam and essay?

    b)  Create a table counting how many students earned each grade level for each assessment (e.g., A1, A2, etc).

    c)  Now create a table counting how many students earned each grade for each assessment, collapsing across levels within an alphabet grade (e.g., A, B, C).

    d)  What proportion of students earned an A on both the exam and the essay?

3.  What is the relationship between students' grades on the essay and the exam? Use `ggplot` to create a plot of this relationship.

## 
