---
title: "Modules"
---

## Overview

To the left, you can find links to all of the course modules. Click one to get started.

::: callout-tip
See [BruinLearn](http://bruinlearn.ucla.edu) for the complete **course syllabus**, including information about course policies, grading, office hours, and more!
:::

## Schedule for Spring 2026

+----------+--------------+-----------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| **Week** | **Date**     | **Module**                                                | **Description**                                                                                        |
+:========:+:============:+===========================================================+========================================================================================================+
| 1        | March 31,\   | [Intro to Programming with R](01_intro.html)              | Installation and familiarization with R and RStudio interface;\                                        |
|          | April 2      |                                                           | Data organization, reproducible scientific programming                                                 |
+----------+--------------+-----------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 2        | April 7, 9   | Programming Foundations:\                                 | Variables, vectors, branches, loops, functions                                                         |
|          |              | [Part 1](02_programming-foundations-1.html)\              |                                                                                                        |
|          |              | [Part 2](03_programming-foundations-2.html)               |                                                                                                        |
+----------+--------------+-----------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 3        | April 14, 16 | [Data Visualization](04_data-visualization.html)          | Exploratory data visualization with ggplot, customizing plots                                          |
+----------+--------------+-----------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 4        | April 21, 21 | [Data Summaries](05_data-summaries.html)                  | Importing and summarizing data, tidyverse pipes                                                        |
+----------+--------------+-----------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 5        | April 28, 30 | [Data Wrangling](06_data-wrangling.html)                  | Selecting and filtering data, creating new variables                                                   |
+----------+--------------+-----------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 6        | May 5, 7     | [Data Tidying](07_data-tidying.html)                      | What is "tidy" data and how do we get it                                                               |
+----------+--------------+-----------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 7        | May 12, 14   | [Data Relations](08_data-relations.html)\                 | Combining datasets;\                                                                                   |
|          |              | + Data Workshop                                           | Working with project datasets                                                                          |
+----------+--------------+-----------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 8        | May 19, 21   | [Statistical Analysis in R](09_statistical-analysis.html) | Basic statistical analysis in R, including t-tests, ANOVAs, and regression analyses on sample datasets |
+----------+--------------+-----------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 9        | May 26, 28   | [Intro to Machine Learning](10_machine-learning.html)     | Simple machine learning models for classifying psychological outcomes                                  |
+----------+--------------+-----------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 10       | June 2, 4    | Project Presentations                                     | [**Final projects** **due**](projects/final-project.html)                                              |
+----------+--------------+-----------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
